// Transcription's words in Hebrew, Yiddish and English: transcribe.ivrit.ai's own
// (with its server's error keys), now the app's. tr() falls back to Hebrew, as
// transcribe.ivrit.ai did, and then to the key itself.

const he = {
  title: "תמלול בעזרת ivrit.ai",
  themeToggle: "החלף מצב תאורה",
  settings: "הגדרות",
  language: "שפה",
  languageHebrew: "עברית",
  languageYiddish: "ייִדיש",
  languageEnglish: "אנגלית",
  dropPrompt: "גרור קובץ לכאן או לחץ לבחירת קובץ",
  transcribe: "תמלל",
  copyText: "העתק את הטקסט",
  downloads: "הורדות",
  downloadAs: "הורד כ...",
  wordDocx: "Word DOCX",
  contactUs: "רוצים ליצור קשר? אנחנו כאן",
  donateAsk: "רוצים לתרום לנו?",
  privacyTos: "מדיניות פרטיות ותנאי שימוש",
  settingsHeader: "הגדרות",
  settingsRunpod: "הגדרות RunPod",
  runpodKeyLabel: "RunPod API Key:",
  runpodKeyPlaceholder: "הכנס את ה-API Key שלך",
  runpodHelpWatch: "לצפייה בסרטון הסבר",
  runpodHelpText: "הזנת מפתח פרטי מאפשרת שימוש במשאבים פרטיים לעיבוד מהיר יותר.",
  settingsWithRunpodSaved: "הגדרות (הגדרות RunPod שמורות)",
  balanceLabel: "יתרה",
  remainingQuotaLabel: "מכסה נותרת",
  quotaLoadingError: "שגיאה בטעינת המכסה",
  howToGetMoreQuota: "הגדלת מכסה",
  hours: "שעות",
  minutes: "דקות",
  loading: "טוען...",
  displaySettings: "הגדרות תצוגה",
  timestampsLabel: "קודי זמן:",
  timestampsNone: "ללא קודי זמן",
  timestampsNoneHelp: "רק הטקסט ללא זמנים",
  timestampsSegments: "כולל קודי זמן",
  timestampsSegmentsHelp: "זמני התחלה וסיום, לפי פורמט הטקסט",
  diarizationLabel: "הפרדת דוברים:",
  diarizationEnabled: "הצג דוברים",
  diarizationEnabledHelp: "הצג תוויות דוברים ושורות חדשות עם החלפת דובר",
  diarizationDisabled: "הסתר דוברים",
  diarizationDisabledHelp: "הצג רק טקסט ללא תוויות דוברים",
  save: "שמור",
  cancel: "ביטול",
  clear: "נקה הגדרות",
  signOut: "התנתקות",
  signOutError: "לא הצלחנו להתנתק. יש לבדוק את החיבור לאינטרנט ולנסות שוב.",
  fileSize: "גודל קובץ",
  removeFile: "הסר קובץ",
  saveAudioInDrive: "שמור אודיו ל-Google Drive",
  saveAudio: "שמור אודיו",
  whatDoesThisMean: "מה זה אומר?",
  saveAudioInfoText: "שמירת קובץ השמע תאפשר בקרוב גם קריאה מתוזמנת של התמלול, יחד עם שמע מסונכרן.\n\nקובץ השמע נשמר על כונן גוגל שלך בלבד, לא על השרתים שלנו.",
  fileRemovedSuccess: "קובץ הוסר בהצלחה",
  fileSelectedSuccess: "קובץ נבחר בהצלחה",
  fileTooLarge: "הקובץ גדול מדי. הגודל המקסימלי המותר הוא {size}",
  usingRunpod: "משתמש בהגדרות RunPod מותאמות אישית...",
  uploading: "מעלה את הקובץ...",
  uploadingProgress: "מעלה את הקובץ... {progress}%",
  uploadedStarting: "קובץ הועלה. מתחיל בתמלול...",
  uploadTranscodingPending: "ממתין להתחלת המרת השמע...",
  uploadTranscodingStarted: "ממיר את קובץ השמע...",
  uploadTranscodingProgress: "ממיר את קובץ השמע... {progress}%",
  uploadQueuePositionDetail: "העבודה בתור במקום {position} ({jobType})",
  uploadQueueEtaDetail: "זמן משוער לתחילת התמלול: {eta}",
  uploadTranscodingComplete: "המרת השמע הסתיימה. העבודה הועברה לתמלול.",
  uploadError: "שגיאה בהעלאת הקובץ. אנא נסה שוב.",
  queuePosition: "בתור במקום {position}. זמן משוער להתחלה: {eta}",
  jobTypePrefix: "סוג עבודה: {jobType}",
  jobTypeShort: "קצרה",
  jobTypeLong: "ארוכה",
  jobTypePrivate: "פרטית",
  waitingMsg: "בזמן שאתם ממתינים, אנו מזכירים ש-ivrit.ai הוא פרויקט ללא מטרות רווח.\nכל השירותים שלנו, כולל שירות התמלול בו אתם משתמשים כרגע, ניתנים בחינם.\n\nנודה אם תוכלו לתרום בכדי שנוכל להנגיש את השירות ליותר משתמשים.\n\nניתן לתרום דרך לינק לפטראון בתחתית המסך.\n\nתודה!",
  transcribing: "מתמלל... {progress}%",
  statusError: "אירעה שגיאה בבדיקת סטטוס העבודה",
  verifyChecking: "בודק...",
  runpodSettingsSaved: "הגדרות RunPod נשמרו בהצלחה",
  runpodEndpointWait: "Endpoint חדש נוצר או עודכן. אנא המתן 3 דקות לפני העלאת קבצים.",
  settingsSaved: "הגדרות נשמרו בהצלחה",
  settingsCleared: "כל ההגדרות נמחקו בהצלחה",
  balanceLoadingError: "שגיאה בטעינה",
  runpodServerConnError: "שגיאה: לא ניתן להתחבר לשרת RunPod.\nאנא בדוק את החיבור לאינטרנט ונסה שוב.",
  runpodVerifyError: "שגיאה בבדיקת הגדרות RunPod.",
  endpointCheckError: "שגיאה בבדיקת ה-endpoint:",
  runpodTokenUnsavedWarning: 'מפתח ה-RunPod לא נשמר. לחץ על "שמור" כדי להחיל אותו.',
  runpodKeySavedHint: "מפתח שמור המסתיים ב-…{hint}",
  removeRunpodKey: "הסר מפתח RunPod",
  runpodKeyRemoved: "מפתח ה-RunPod הוסר",
  runpodKeyLoadFailed: "לא הצלחנו לטעון את מפתח ה-RunPod השמור שלך. אנא הזן אותו מחדש בהגדרות.",
  runpodKeyMigrationFailed: "לא הצלחנו לאמת את מפתח ה-RunPod השמור שלך. אנא הזן אותו מחדש בהגדרות.",
  errorReportTemplate: "אם השגיאה נמשכת, אנא שלחו דיווח לכתובת info@ivrit.ai עם הפרטים הבאים:\n- כתובת האימייל שלכם\n- זמן השגיאה: {time}\n- פרטי השגיאה: {details}",
  transcriptFooter: "תומלל באמצעות שירות התמלול של ivrit.ai",
  copySuccess: "הטקסט הועתק ללוח בהצלחה",
  docxLibMissing: "ספריית יצירת המסמך לא נטענה. בדקו את החיבור ונסו שוב.",
  docxCreateError: "שגיאה ביצירת קובץ Word. אנא נסה שוב.",
  exportError: "שגיאה בייצוא נתוני התמלול",
  exitWarning: "התמלול עדיין פעיל. יציאה מהדף תפסיק את התמלול. האם אתה בטוח שברצונך לצאת?",
  transcriptHeaderDocx: "תמלול",
  speaker: "דובר {num}",
  speakerUnknown: "דובר לא מזוהה",
  errorPrefix: "שגיאה",
  unitBytes: "Bytes",
  unitKB: "KB",
  unitMB: "MB",
  unitGB: "GB",
  textFormatSegmentsTitle: "פורמט הטקסט: פסקאות נפרדות",
  textFormatContinuousTitle: "פורמט הטקסט: טקסט רציף",
  filesSelectedCount: "{count} קבצים נבחרו",
  filesSelectedSuccess: "{count} קבצים נבחרו בהצלחה",
  batchStarting: "מתחיל עיבוד אצווה של {count} קבצים...",
  batchUploading: "מעלה {index}/{total}: {filename}",
  batchQueued: "{count} קבצים נשלחו לתמלול בהצלחה. התוצאות יופיעו ב\"הקבצים שלי\" כשיסתיימו.",
  batchTranscribing: "מתמלל ({index}/{total}) {filename} · {progress}%",
  batchDone: "האצווה הושלמה",
  docxDownloaded: "קובץ DOCX ירד: {filename}",
  tabTranscribe: "תמלול חדש",
  tabMyFiles: "הקבצים שלי",
  viewTitle: "תמלול",
  tabViewer: "צפייה",
  openDataDir: "הצג נתיב תיקייה",
  dataDirCopied: "הנתיב הוצג",
  dataDirWarning: "שינוי, מחיקה או שינוי שם של קבצים בתיקייה זו עלול לפגוע בנתונים המאוחסנים שלך באופן בלתי הפיך.\n\nיש לנהוג בזהירות רבה.\n\nלהמשיך?",
  filesLoading: "טוען קבצים...",
  filesEmpty: "עדיין לא שמרת תמלולים",
  filesLoadError: "שגיאה בטעינת הקבצים",
  loadingFile: "טוען קובץ...",
  filesDownloading: "מוריד קובץ...",
  filesDownloadSuccess: "הקובץ הורד בהצלחה",
  filesDownloadError: "שגיאה בהורדת הקובץ",
  backToFiles: "חזרה לרשימה",
  renameFile: "שנה שם",
  fileRenamedSuccess: "השם שונה בהצלחה",
  renameError: "שגיאה בשינוי השם",
  saving: "שומר...",
  discardEditsConfirm: "לבטל את השינויים שלא נשמרו בתמלול?",
  editsLoadError: "לא הצלחנו לטעון את העריכות השמורות של התמלול. יש לרענן את הדף ולנסות שוב.",
  editorLoadError: "לא הצלחנו לטעון את העורך. יש לבדוק את החיבור לאינטרנט ולרענן את הדף.",
  restoreEditDraftConfirm: "נמצאו שינויים שלא נשמרו בתמלול הזה מהפעם הקודמת. לשחזר אותם? (ביטול ימחק אותם)",
  transcriptionQueued: "הקובץ נשלח לתמלול בהצלחה.",
  transcriptionInProgress: "תמלול בתהליך",
  batchFailed: "כל הקבצים נכשלו",
  deleteFile: "מחק קובץ",
  quotaRefunded: "הדקות הוחזרו למכסה שלך",
  deleteConfirm: 'האם אתה בטוח שברצונך למחוק את "{filename}"?\n\nפעולה זו אינה הפיכה.',
  fileDeletedSuccess: "הקובץ נמחק בהצלחה",
  deleteError: "שגיאה במחיקת הקובץ",
  deleting: "מוחק...",
  recordAudio: "הקלט אודיו",
  recordMicOnly: "הקלט ממיקרופון בלבד",
  recordMicAndScreen: "הקלט מיקרופון + מסך",
  recordScreenOnly: "הקלט ממסך בלבד",
  stopRecording: "עצור הקלטה",
  downloadRecording: "הורד הקלטה",
  transcribeRecording: "תמלל הקלטה",
  discardRecording: "מחק הקלטה",
  recordingDownloaded: "ההקלטה הורדה בהצלחה",
  recordingDiscarded: "ההקלטה נמחקה",
  recordingNotBackedUp: "לא ניתן לגבות את ההקלטה בדפדפן, ולכן היא נשמרת בזיכרון בלבד. מומלץ להוריד אותה בסיום ההקלטה.",
  recoveredRecordingFound: "נמצאה הקלטה שטרם נשלחה לתמלול",
  recoveredRecordingInterrupted: "נמצאה הקלטה שנקטעה לפני שהסתיימה",
  recoveredRecordingHint: "ההקלטה שמורה בדפדפן שלך. אפשר לתמלל אותה עכשיו, להוריד אותה למחשב, או למחוק אותה.",
  recordingReadyToTranscribe: "ההקלטה מוכנה לתמלול. לחץ על \"תמלל\" להמשך.",
  recordingReadFailed: "לא ניתן לטעון את ההקלטה כרגע, אך היא שמורה בדפדפן. רענן את הדף כדי לשחזר אותה.",
  pushPromptTitle: "לקבל התראה כשהתמלול מוכן?",
  pushPromptBody: "התמלול ממשיך גם אם תסגרו את הדפדפן. נוכל לשלוח לכם התראה ברגע שהוא מוכן.",
  pushPromptYes: "כן, עדכנו אותי",
  pushPromptNo: "לא עכשיו",
  pushPromptDontAsk: "אל תשאלו אותי שוב",
  pushEnabled: "נשלח לכם התראה כשהתמלול יהיה מוכן.",
  pushDenied: "לא הצלחנו להפעיל התראות. אפשר לאשר אותן בהגדרות הדפדפן.",
  installApp: "התקנה",
  installTitle: "התקנת האפליקציה",
  installWhy: "האפליקציה תיפתח ממסך הבית כמו כל אפליקציה אחרת.",
  installWhyNotifications: "באייפון זו גם הדרך היחידה לקבל התראה כשהתמלול מוכן.",
  installStepsIos: "פתחו את תפריט השיתוף בסרגל הכלים של Safari ובחרו ״הוספה למסך הבית״.",
  installDone: "הבנתי",
  installed: "האפליקציה הותקנה.",
  micPermissionDenied: "הגישה למיקרופון או לאודיו המערכת נדחתה. אנא אפשר גישה בהגדרות הדפדפן.",
  micError: "שגיאה בגישה לאודיו. אנא ודא שההתקנים מחוברים ומופעלים.",
  recordingMicOnlyWarning: "הקלטה ממיקרופון בלבד (אודיו מערכת לא נבחר)",
  screenAudioNotSelected: "לא נבחר אודיו מערכת. אנא סמן \"שתף אודיו\" בתיבת הדו-שיח.",
  screenAudioError: "שגיאה בגישה לאודיו המערכת. אנא נסה שוב.",
  // Server error messages
  errorJobAlreadyActive: "יש לך כבר עבודה בתור או בביצוע. אנא המתן לסיומה לפני העלאת קובץ חדש.",
  errorRateLimitExceeded: "עברת את מגבלת השימוש החופשי. אנא המתן {minutes} דקות לפני העלאת קובץ חדש, או השתמש במפתח פרטי בעזרת ההוראות בסרטון הבא: https://youtu.be/xr8RQRFERLs",
  errorFileTooLargeForFreeService: "הקובץ המבוקש גדול מדי ועובר את מגבלת השימוש החופשי הכוללת. אנא השתמש במפתח פרטי בעזרת ההוראות בסרטון הבא: https://youtu.be/xr8RQRFERLs",
  errorServerBusy: "השרת עמוס כרגע. אנא נסה שוב מאוחר יותר.",
  errorDrivePermissionsRequired: "השירות דורש הרשאות Google Drive כדי לשמור את התמלולים שלך. אנא אשר את כל ההרשאות המבוקשות כדי להמשיך.",
  errorServiceUnavailable: "השירות כרגע לא פעיל. אנא נסה שוב מאוחר יותר.",
  errorNoFileSelected: "לא נבחר קובץ. אנא בחר קובץ להעלאה.",
  errorEmptyFilename: "שם הקובץ ריק. אנא בחר קובץ תקין.",
  errorFileTooLarge: "הקובץ גדול מדי. הגודל המקסימלי המותר הוא {size}.",
  errorUploadFailed: "העלאת הקובץ נכשלה: {details}",
  errorUnsupportedFileType: "סוג הקובץ {type} אינו נתמך. אנא העלה קובץ אודיו או וידאו תקין.",
  errorTranscodingFailed: "המרת הקובץ נכשלה. ייתכן שסוג הקובץ אינו נתמך או שהקובץ פגום. אנא נסה עם קובץ אחר.",
  errorCannotReadDuration: "לא ניתן לקרוא את משך הקובץ. אנא ודא שהקובץ תקין ונסה שוב.",
  errorFileTooLong: "הקובץ ארוך מדי. המשך המקסימלי המותר הוא {maxHours} שעות ({maxSeconds} שעות), אך הקובץ שלך הוא {fileHours} שעות.",
  errorBatchLimitReached: "הגעת למגבלת העבודות המקבילות. אנא המתן לסיום חלק מהעבודות לפני העלאת קבצים נוספים.",
  batchLimitExceeded: "נבחרו יותר מדי קבצים. רק {limit} הקבצים הראשונים יעובדו.",
  errorTranscodingJobActive: "יש לך כבר עבודה בתהליך המרה. אנא המתן לסיומה לפני העלאת קובץ חדש.",
  errorDriveNotConnected: "לא זוהה חיבור ל-Google Drive. אנא התחבר מחדש.",
  errorDrivePermissionsInsufficient: "הרשאות Google Drive חסרות. אנא התנתק והתחבר מחדש כדי לאשר גישה לדרייב.",
  errorDriveAccessFailed: "שגיאה בגישה ל-Google Drive. אנא נסה שוב מאוחר יותר.",
  errorDriveUnavailable: "לא ניתן לגשת ל-Google Drive. אנא התחבר מחדש.",
  errorDriveStorageFull: "ה-Google Drive שלך מלא, ולכן לא ניתן לשמור את התמלול. פנו מקום ונסו שוב.",
  errorMediaLost: "הקובץ לא נשמר אצלנו עד שהגיע תורו. שלחו אותו שוב.",
  errorLanguageRequiresPrivateKey: "שפה זו זמינה רק לשימוש עם מפתח RunPod פרטי.",
  errorEndpointCheckFailed: "שגיאה בבדיקת ה-endpoint: {details}",
  errorEndpointCreated: "נוצר endpoint חדש עבור המפתח שלך. אנא המתן 3 דקות לפני העלאת קבצים.",
  errorEndpointUpdated: "ה-endpoint שלך עודכן. אנא המתן 3 דקות לפני העלאת קבצים.",
  errorMissingSaveAudio: "Missing save_audio parameter",
  errorMissingLanguage: "Missing language",
  errorUnsupportedLanguage: "Unsupported language",
  errorMissingRunpodToken: "Missing RunPod token",
  errorNotAuthenticated: "Not authenticated with Google Drive",
  errorUserEmailNotFound: "User email not found",
  errorTocLoadFailed: "Failed to load TOC",
  errorResultsNotFound: "Results file not found",
  errorResultsDownloadFailed: "Failed to download results",
  errorAudioNotFound: "Audio file not found",
  errorAudioDownloadFailed: "Failed to download audio",
  errorMissingResultsId: "Missing results_id",
  errorMissingNewFilename: "Missing results_id or new_filename",
  errorFilenameEmpty: "Filename cannot be empty",
  errorFileNotInToc: "File not found in TOC",
  errorTocUpdateFailed: "Failed to update TOC",
  errorInternalServer: "Internal server error",
  errorBalanceFetchFailed: "Failed to fetch balance",
  errorRunpodKeyVerifyFailed: "לא הצלחנו לאמת את מפתח ה-RunPod. אנא בדוק שהמפתח נכון ונסה שוב.",
  errorRunpodKeySaveFailed: "לא הצלחנו לשמור את מפתח ה-RunPod ב-Google Drive שלך. אנא נסה שוב.",
  errorRunpodKeyRemoveFailed: "לא הצלחנו להסיר את מפתח ה-RunPod. אנא נסה שוב.",
  errorInvalidJson: "Invalid JSON body",
  errorMissingFileSize: "Missing file_size",
  errorInvalidFileSize: "Invalid file_size",
  tabStats: "סטטיסטיקות",
  statsForNerds: "סטטיסטיקות לחנונים",
  transcriptionStatistics: "סטטיסטיקות תמלול",
  totalTime: "זמן כולל",
  totalWords: "מילים",
  totalLetters: "אותיות",
  wordsPerMinute: "מילים לדקה",
  lettersPerMinute: "אותיות לדקה",
  avgTimeBetweenSpeakers: "זמן ממוצע בין דוברים (שניות)",
  medianTimeBetweenSpeakers: "זמן חציוני בין דוברים (שניות)",
  speakerTimeDistribution: "התפלגות זמן דיבור לפי דובר",
  unknownSpeaker: "לא ידוע",
  donateData: "תרומת נתונים",
  donateDataTitle: "תודה על התרומה!",
  donateDataMessage: "בתרום נתונים אלה, אתה מאשר שיש לך הרשאות לשחרר הן את הקול והן את הטקסט תחת רישיון ivrit.ai v2.",
  donateDataCheckbox: "קראתי ואני מסכים",
  donateDataLicenseLink: "רישיון ivrit.ai v2",
  donateDataSubmit: "שלח",
  donateDataSuccess: "תודה! הנתונים נתרמו בהצלחה.",
  donateDataError: "שגיאה בתרומת הנתונים. אנא נסה שוב.",
  donateDataAlreadyDonated: "נתונים אלה כבר נתרמו.",
  errorMissingResultsId: "חסר results_id",
  errorDonateNoAudio: "קובץ אודיו לא נמצא לתרומה",
  errorDonateNoTranscript: "תמלול לא נמצא לתרומה",
  errorDonateCheckboxRequired: "יש לאשר את תיבת הסימון",
  errorAlreadyDonated: "נתונים אלה כבר נתרמו",
  // Input method labels
  inputUploadFile: "העלאת קובץ",
  inputYoutube: "YouTube",
  inputRecord: "הקלטה",
  // YouTube
  orSeparator: "או",
  youtubeUrlPlaceholder: "הדבק קישור YouTube כאן",
  youtubeUrlPaste: "הדבק",
  youtubeRightsTitle: "אישור זכויות",
  youtubeRightsMessage: "הורדת תוכן מ-YouTube עשויה להפר את זכויות היוצרים ואת תנאי השירות של YouTube. אנא ודא שיש לך את הזכויות הנדרשות להוריד ולתמלל תוכן זה.",
  youtubeRightsCheckbox: "אני מאשר שיש לי את הזכויות להוריד ולתמלל תוכן זה",
  youtubeRightsSubmit: "המשך",
  youtubeDownloading: "מוריד אודיו מ-YouTube...",
  youtubeDownloadingProgress: "מוריד... {progress}%",
  youtubeDownloadComplete: "ההורדה הסתיימה. ממיר אודיו...",
  errorInvalidYoutubeUrl: "קישור YouTube לא תקין",
  errorYoutubeDownloadFailed: "הורדת הקובץ מ-YouTube נכשלה. ייתכן שהסרטון אינו זמין או שיש בעיה בחיבור.",
  errorYoutubeRightsNotConfirmed: "יש לאשר את הזכויות לפני ההורדה",
}

const yi = {
  title: "טראַנסקריפּציע דורך ivrit.ai",
  themeToggle: "באַשטייערן ליכט/טונקל מאָדע",
  settings: "איינשטעלונגען",
  language: "שפּראַך",
  languageHebrew: "עברית",
  languageYiddish: "ייִדיש",
  languageEnglish: "ענגליש",
  dropPrompt: "ציע לאָז דאָ אַ טעקע אָדער דריקט צו אויסקלייבן",
  transcribe: "טראַנסקריבער",
  copyText: "קאָפּירן דעם טעקסט",
  downloads: "אַראָפלאָדן",
  downloadAs: "אַראָפלאָדן ווי...",
  wordDocx: "Word DOCX",
  contactUs: "ווילט איר זיך קאָנטאַקטירן? מיר זײַנען דאָ",
  donateAsk: "ווילט איר אונדז שטיצן?",
  privacyTos: "פּריוואַטקייט פּאָליסי און תנאי־ניצול",
  settingsHeader: "איינשטעלונגען",
  settingsRunpod: "RunPod איינשטעלונגען",
  runpodKeyLabel: "RunPod API קלעף:",
  runpodKeyPlaceholder: "אַרײַנלייגן אייערן API קלעף",
  runpodHelpWatch: "קוקן דערקלער־ווידעא",
  runpodHelpText: "אַ פּערזענלעכער שליסל דערמעגלעכט שנעלערע באַהאַנדלונג אויף אייערע רעסורסן.",
  settingsWithRunpodSaved: "איינשטעלונגען (RunPod־אויפֿהיטונגען אַנטהאַלטן)",
  balanceLabel: "באַלאַנס",
  remainingQuotaLabel: "איבעריקע קוואָטע",
  quotaLoadingError: "טעות בײַם לאָדן קוואָטע",
  howToGetMoreQuota: "קוואָטע־פֿאַרגרעסערונג",
  hours: "שעה",
  minutes: "מינוט",
  loading: "לאָדט...",
  displaySettings: "וויזועל־איינשטעלונגען",
  timestampsLabel: "צײַט־קאָדן:",
  timestampsNone: "אָן צײַט־קאָדן",
  timestampsNoneHelp: "בלויז דער טעקסט אָן צײַטן",
  timestampsSegments: "מיט צײַט־קאָדן",
  timestampsSegmentsHelp: "אָנפֿאַנג און סוף, לויט פֿאָרמאַט",
  diarizationLabel: "אָפּטיילונג פֿון רעדנדיקע:",
  diarizationEnabled: "ווײַזן רעדנדיקע",
  diarizationEnabledHelp: "ווײַזן טאַגלען און נײַע שורות בײַ טויש",
  diarizationDisabled: "באַהאַלטן רעדנדיקע",
  diarizationDisabledHelp: "ווײַזן בלויז טעקסט אָן טאַגלען",
  save: "אויפֿהיטן",
  cancel: "אַנולירן",
  clear: "באַוואַרפֿן איינשטעלונגען",
  signOut: "אַרויסלאָגירן",
  signOutError: "מיר האָבן ניט געקענט אַרויסלאָגירן. ביטע קאָנטראָלירט אײַער פֿאַרבינדונג און פּרוּווט ווידער.",
  fileSize: "טעקע־גרייס",
  removeFile: "אויסמעקן טעקע",
  saveAudioInDrive: "היט אַודיאָ צו Google Drive",
  saveAudio: "היט אַודיאָ",
  whatDoesThisMean: "וואָס הייסט דאָס?",
  saveAudioInfoText: "אויפֿהיטן די קלאַנג־טעקע וועט באַלד אויך דערמעגלעכן אַ סינכראָניזירטע לייענען פֿון דער טראַנסקריפּציע, מיט דער קלאַנג.\n\nדי קלאַנג־טעקע ווערט אויפֿגעהיט נאָר אויף דײַן Google כונן, נישט אויף אונדזערע סערווירערס.",
  fileRemovedSuccess: "טעקע איז געלאָשן געוואָרן מיט הצלחה",
  fileSelectedSuccess: "טעקע איז געראָטן אויסגעקליבן",
  fileTooLarge: "די טעקע איז צו גרויַס. מעגלעכער העכסטער איז {size}",
  usingRunpod: "נוצט פּערזענלעכע RunPod איינשטעלונגען...",
  uploading: "אַרויפֿלאָדט די טעקע...",
  uploadingProgress: "אַרויפֿלאָדט די טעקע... {progress}%",
  uploadedStarting: "טעקע אַרויפֿגעלאָדן. הייבט אָן טראַנסקריפּציע...",
  uploadTranscodingPending: "וואַרט אויף אָנהייב פֿון דער אַודיאָ־קאָנווערציע...",
  uploadTranscodingStarted: "קאָנווערטירט די אַודיאָ...",
  uploadTranscodingProgress: "קאָנווערטירט די אַודיאָ... {progress}%",
  uploadQueuePositionDetail: "די אַרבעט איז אין דער ריי אָרט {position} ({jobType})",
  uploadQueueEtaDetail: "אומגעפֿערלעכע אָנהייב־צײַט: {eta}",
  uploadTranscodingComplete: "די קאָנווערציע איז געענדיקט. די אַרבעט גייט ווייטער צום טראַנסקריפּציע־תּור.",
  uploadError: "א טעות בעת אַרויפֿלאָדן. ביטע פּרוּווט נאָך אַ מאָל.",
  queuePosition: "אין דער ריי אָרט {position}. אַפּראָקס. אָנהייב־צײַט: {eta}",
  jobTypePrefix: "אַרבעט־סאָרט: {jobType}",
  jobTypeShort: "קורץ",
  jobTypeLong: "לאַנג",
  jobTypePrivate: "פּריוואַט",
  waitingMsg: "ווען איר וואַרט, געדענקט אַז ivrit.ai איז אַ נאַן־פּראָפֿיט.\nאַלע אונדזערע דינען, אַרײַנגערעכנט דעם טראַנסקריפּציע־דינסט, זײַנען בחינם.\n\nביטע שטיצט אונדז כּדי צוצוגעבן דעם דינסט פאר מער ניצערס.\n\nמען קען שטיצן דורך פּאַטרעאָן לינק אונטן.\n\nאַ דאַנק!",
  transcribing: "טראַנסקריבירט... {progress}%",
  statusError: "א טעות בײַם קאָנטראָלירן אַרבעט־סטאַטוס",
  verifyChecking: "באַשטעטיקט...",
  runpodSettingsSaved: "RunPod איינשטעלונגען געוואָרן געראַטעוועט",
  runpodEndpointWait: "אַנדערש אַ נײַער/דערהײַנטיקער Endpoint. וואַרטט 3 מינוט פֿריִער",
  settingsSaved: "איינשטעלונגען געראַטעוועט",
  settingsCleared: "אַלע איינשטעלונגען ווערן געלייגט צוריק",
  balanceLoadingError: "טעות בײַם לאָדן",
  runpodServerConnError: "טעות: מ׳קען זיך נישט פֿאַרבינדן צו RunPod סערוויר.\nביטע פּרוּווט ווידער.",
  runpodVerifyError: "טעות בײַם באַשטעטיקן RunPod איינשטעלונגען.",
  endpointCheckError: "טעות בײַם קאָנטראָלירן Endpoint:",
  runpodTokenUnsavedWarning: 'RunPod קלעף איז נישט אויפֿגעהיט. דריקט "אויפֿהיטן" כדי עס צו אַקטיוויזירן.',
  runpodKeySavedHint: "אויפֿגעהיטענער קלעף וואָס ענדיקט זיך מיט …{hint}",
  removeRunpodKey: "אַראָפּנעמען RunPod קלעף",
  runpodKeyRemoved: "RunPod קלעף איז אַראָפּגענומען געוואָרן",
  runpodKeyLoadFailed: "מיר האָבן נישט געקענט לאָדן אײַער אויפֿגעהיטענעם RunPod קלעף. ביטע גיט אים אַרײַן נאָך אַ מאָל אין די איינשטעלונגען.",
  runpodKeyMigrationFailed: "מיר האָבן נישט געקענט באַשטעטיקן אײַער אויפֿגעהיטענעם RunPod קלעף. ביטע גיט אים אַרײַן נאָך אַ מאָל אין די איינשטעלונגען.",
  errorReportTemplate: "אויב דער טעות בלײַבט, ביטע שיקט אַ רעפּאָרט צו info@ivrit.ai מיט די דעטאַלן:\n- אייער אימעיל־אַדרעס\n- צײַט פֿון טעות: {time}\n- דעטאַלן: {details}",
  transcriptFooter: "טראַנסקריבירט דורך ivrit.ai'ס דינסט",
  copySuccess: "טעקסט איז קאַפּירט געוואָרן",
  docxLibMissing: "די דאָקומענט־ביבליאָטעק איז נישט געלאָדן. פּרוּווט ווידער.",
  docxCreateError: "טעות בײַם שאַפֿן Word טעקע. פּרוּווט ווידער.",
  exportError: "טעות בײַם אַן־פיר פֿון טראַנסקריפּציע־דאַטן",
  exitWarning: "טראַנסקריפּציע לויפֿט נאָך. אַרויסגיין וועט אָפּשטעלן. זענט איר זיכער?",
  transcriptHeaderDocx: "טראַנסקריפּציע",
  speaker: "רעדנדיקער {num}",
  speakerUnknown: "ניט־ידענטיפֿיצירטער רעדנדיקער",
  errorPrefix: "טעות",
  unitBytes: "Bytes",
  unitKB: "KB",
  unitMB: "MB",
  unitGB: "GB",
  textFormatSegmentsTitle: "טעקסט־פֿאָרמאַט: באַזונדערע פּאַראַגראַפֿן",
  textFormatContinuousTitle: "טעקסט־פֿאָרמאַט: קאַנטיניואַלע שורה",
  filesSelectedCount: "{count} טעקעס אויסגעקליבן",
  filesSelectedSuccess: "{count} טעקעס געראָטן אויסגעקליבן",
  batchStarting: "הייבט אָן אַ באַטש פֿון {count} טעקעס...",
  batchUploading: "אַרויפֿלאָדט {index}/{total}: {filename}",
  batchQueued: "{count} טעקעס זענען אַרײַנגעשיקט צום טראַנסקריבירן. רעזולטאַטן וועלן אויפֿטרעטן אין \"מײַנע טעקעס\".",
  batchTranscribing: "טראַנסקריבירט ({index}/{total}) {filename} · {progress}%",
  batchDone: "באַטש פאַרענדיקט",
  docxDownloaded: "DOCX אַראָפּלאָדן: {filename}",
  tabTranscribe: "נײַע טראַנסקריפּציע",
  tabMyFiles: "מײַנע טעקעס",
  viewTitle: "טראַנסקריבירן",
  tabViewer: "באַקוקן",
  openDataDir: "קאָפּירן טעקע־וועג",
  dataDirCopied: "דער וועג איז קאָפּירט",
  dataDirWarning: "ענדערן, אויסמעקן אָדער באַנענען טעקעס אין דעם טעקע קען באַשעדיקן אייערע אויפֿגעהיטע דאַטן אומאומקערלעך.\n\nביטע זייט זייער אָפּגעהיט.\n\nפֿאָרזעצן?",
  filesLoading: "לאָדט טעקעס...",
  filesEmpty: "איר האָט נאָך נישט אויפֿגעהיט טראַנסקריפּציעס",
  filesLoadError: "טעות בײַם לאָדן טעקעס",
  loadingFile: "לאָדט טעקע...",
  filesDownloading: "אַראָפּלאָדט טעקע...",
  filesDownloadSuccess: "טעקע אַראָפּלאָדן געראָטן",
  filesDownloadError: "טעות בײַם אַראָפּלאָדן טעקע",
  backToFiles: "צוריק צו רשימה",
  renameFile: "בײַטן נאָמען",
  fileRenamedSuccess: "נאָמען געענדערט געראָטן",
  renameError: "טעות בײַם ענדערן נאָמען",
  saving: "היט אַוועק...",
  discardEditsConfirm: "אַוועקוואַרפֿן די ניט־אויפֿגעהיטענע ענדערונגען אין דער טראַנסקריפּציע?",
  editsLoadError: "מיר האָבן ניט געקענט לאָדן אײַערע אויפֿגעהיטענע ענדערונגען פֿאַר דער טראַנסקריפּציע. ביטע לאָדט איבער דעם בלאַט און פּרוּווט ווידער.",
  editorLoadError: "מיר האָבן ניט געקענט לאָדן דעם רעדאַקטאָר. ביטע קאָנטראָלירט אײַער פֿאַרבינדונג און לאָדט איבער דעם בלאַט.",
  restoreEditDraftConfirm: "מע האָט געפֿונען ניט־אויפֿגעהיטענע ענדערונגען אין דער טראַנסקריפּציע פֿון דער פֿריִערדיקער סעסיע. צוריקשטעלן זיי? (אָפּזאָגן מעקט זיי אויס)",
  transcriptionQueued: "די טעקע איז געשיקט געוואָרן צו טראַנסקריבירן.",
  transcriptionInProgress: "טראַנסקריפּציע אין פּראָצעס",
  batchFailed: "אַלע טעקעס האָבן דורכגעפֿאַלן",
  deleteFile: "אויסמעקן טעקע",
  quotaRefunded: "די מינוט זענען צוריקגעגעבן געוואָרן צו דיין קוואָטע",
  deleteConfirm: 'ביסטו זיכער אַז דו ווילסט אויסמעקן "{filename}"?\n\nדאָס איז ניט צוריקצודרייען.',
  fileDeletedSuccess: "טעקע איז אויסגעמעקט געוואָרן",
  deleteError: "טעות בײַם אויסמעקן טעקע",
  deleting: "אויסמעקט...",
  recordAudio: "רעקאָרדירן אַודיאָ",
  recordMicOnly: "רעקאָרדירן נאָר פֿון מיקראָפֿאָן",
  recordMicAndScreen: "רעקאָרדירן מיקראָפֿאָן + עקראַן",
  recordScreenOnly: "רעקאָרדירן נאָר פֿון עקראַן",
  stopRecording: "אָפּשטעלן רעקאָרדירונג",
  downloadRecording: "אַראָפּלאָדן רעקאָרדירונג",
  transcribeRecording: "טראַנסקריבירן רעקאָרדירונג",
  discardRecording: "אויסמעקן רעקאָרדירונג",
  recordingDownloaded: "רעקאָרדירונג אַראָפּגעלאָדן געראָטן",
  recordingDiscarded: "רעקאָרדירונג אויסגעמעקט",
  recordingNotBackedUp: "מען קען נישט אויפֿהיטן די רעקאָרדירונג אין בראַוזער, זי בלײַבט נאָר אין זכּרון. לאָדט זי אַראָפּ ווען איר ענדיקט.",
  recoveredRecordingFound: "עס איז דאָ אַ רעקאָרדירונג וואָס איז נאָך נישט געשיקט געוואָרן צו טראַנסקריבירן",
  recoveredRecordingInterrupted: "עס איז דאָ אַ רעקאָרדירונג וואָס איז איבערגעריסן געוואָרן",
  recoveredRecordingHint: "זי איז אויפֿגעהיט אין אײַער בראַוזער. איר קענט זי איצט טראַנסקריבירן, אַראָפּלאָדן, אָדער אויסמעקן.",
  recordingReadyToTranscribe: "רעקאָרדירונג איז גרייט פֿאַר טראַנסקריפּציע. דריקט \"טראַנסקריבער\" צו פֿאָרזעצן.",
  recordingReadFailed: "מען קען איצט נישט לאָדן די רעקאָרדירונג, אָבער זי איז אויפֿגעהיט אין בראַוזער. פֿרישט אויף די בלאַט צו קריגן זי צוריק.",
  pushPromptTitle: "באַקומען אַ מעלדונג ווען די טראַנסקריפּציע איז גרייט?",
  pushPromptBody: "די טראַנסקריפּציע גייט אָן אויך אויב איר פֿאַרמאַכט דעם בראַוזער. מיר קענען אײַך שיקן אַ מעלדונג ווען זי איז גרייט.",
  pushPromptYes: "יאָ, לאָזט מיך וויסן",
  pushPromptNo: "נישט איצט",
  pushPromptDontAsk: "פֿרעגט מיך נישט נאָך אַ מאָל",
  pushEnabled: "מיר וועלן אײַך שיקן אַ מעלדונג ווען די טראַנסקריפּציע איז גרייט.",
  pushDenied: "מיר האָבן נישט געקענט אָנשטעלן מעלדונגען. איר קענט זיי דערלויבן אין די בראַוזער־איינשטעלונגען.",
  installApp: "אינסטאַלירן",
  installTitle: "אינסטאַלירן די אַפּליקאַציע",
  installWhy: "די אַפּליקאַציע וועט זיך עפֿענען פֿונעם היים־עקראַן ווי יעדע אַנדערע אַפּליקאַציע.",
  installWhyNotifications: "אויפֿן iPhone איז דאָס אויך דער איינציקער וועג צו באַקומען אַ מעלדונג ווען די טראַנסקריפּציע איז גרייט.",
  installStepsIos: "עפֿנט דעם טיילן־מעניו אין Safari און קלײַבט אויס ״צוגעבן צום היים־עקראַן״.",
  installDone: "פֿאַרשטאַנען",
  installed: "די אַפּליקאַציע איז אינסטאַלירט געוואָרן.",
  micPermissionDenied: "צוטריט צום מיקראָפֿאָן אָדער סיסטעם־אַודיאָ איז אָפּגעזאָגט געוואָרן. ביטע דערלויבט צוטריט אין בלעטערער־איינשטעלונגען.",
  micError: "טעות בײַם צוטריט צו אַודיאָ. ביטע פֿאַרזיכערט אַז די מכשירים זײַנען פֿאַרבונדן און אַקטיוו.",
  recordingMicOnlyWarning: "רעקאָרדירן נאָר פֿון מיקראָפֿאָן (סיסטעם־אַודיאָ נישט אויסגעקליבן)",
  screenAudioNotSelected: "קיין סיסטעם־אַודיאָ נישט אויסגעקליבן. ביטע טשעקט \"טיילן אַודיאָ\" אין דיאַלאָג.",
  screenAudioError: "טעות בײַם צוטריט צו סיסטעם־אַודיאָ. ביטע פּרוּווט ווידער.",
  // Server error messages
  errorJobAlreadyActive: "איר האָט שוין אַ אַרבעט אין ריי אָדער אין פּראָצעס. ביטע וואַרט ביז זי ענדיקט זיך איידער איר לאָדט אַרויף אַ נײַער טעקע.",
  errorRateLimitExceeded: "איר האָט איבערגעגאַנגען די פֿרײַ־ניצונג־ליבמיט. ביטע וואַרט {minutes} מינוט איידער איר לאָדט אַרויף אַ נײַער טעקע, אָדער ניצט אַ פּריוואַטן שליסל לויט די אינסטרוקציעס אין ווידעא: https://youtu.be/xr8RQRFERLs",
  errorFileTooLargeForFreeService: "דער געבעטענער טעקע איז צו גרויס און גייט איבער די געזאַמטע פֿרײַ־ניצונג־לימיט. ביטע ניצט אַ פּריוואַטן שליסל לויט די אינסטרוקציעס אין ווידעא: https://youtu.be/xr8RQRFERLs",
  errorServerBusy: "דער סערווער איז איצט פֿאַרנומען. ביטע פּרוּווט ווידער שפּעטער.",
  errorDrivePermissionsRequired: "דער דינסט דאַרף Google Drive רשות כּדי צו היטן אייערע טראַנסקריפּציעס. ביטע באַשטעטיקט אַלע געבעטענע רשויות כּדי צו פֿאָרזעצן.",
  errorServiceUnavailable: "דער דינסט איז דערווײַלע נישט פֿאַרהאַן. ביטע פּרוּווט ווידער שפּעטער.",
  errorNoFileSelected: "קיין טעקע איז נישט אויסגעקליבן געוואָרן. ביטע קלײַבט אויס אַ טעקע צו אַרויפֿלאָדן.",
  errorEmptyFilename: "דער טעקע־נאָמען איז ליידיק. ביטע קלײַבט אויס אַ גילטיקע טעקע.",
  errorFileTooLarge: "די טעקע איז צו גרויס. דער מעגלעכער העכסטער איז {size}.",
  errorUploadFailed: "אַרויפֿלאָדן האָט דורכגעפֿאַלן: {details}",
  errorUnsupportedFileType: "טעקע־סאָרט {type} איז נישט געשטיצט. ביטע לאָדט אַרויף אַ גילטיק אַודיאָ אָדער ווידעא טעקע.",
  errorTranscodingFailed: "קאָנווערסיע פֿון דער טעקע האָט דורכגעפֿאַלן. עס קען זײַן אַז די טעקע־סאָרט איז נישט געשטיצט אָדער די טעקע איז פֿאַרדאָרבן. ביטע פּרוּווט מיט אַן אַנדערער טעקע.",
  errorCannotReadDuration: "מ׳קען נישט אויסלייענען די לענג פֿון דער טעקע. ביטע פֿאַרזיכערט אַז די טעקע איז גילטיק און פּרוּווט ווידער.",
  errorFileTooLong: "די טעקע איז צו לאַנג. די מעגלעכע העכסטע לענג איז {maxHours} שעה ({maxSeconds} שעה), אָבער אייער טעקע איז {fileHours} שעה.",
  errorBatchLimitReached: "איר האָט דערגרייכט דעם לימיט פֿון פּאַראַלעלע אַרבעטן. ביטע וואַרט ביז עטלעכע אַרבעטן ענדיקן זיך איידער איר לאָדט אַרויף מער טעקעס.",
  batchLimitExceeded: "צו פֿיל טעקעס אויסגעקליבן. נאָר די ערשטע {limit} טעקעס וועלן באַאַרבעט ווערן.",
  errorTranscodingJobActive: "איר האָט שוין אַ אַרבעט אין קאָנווערסיע־פּראָצעס. ביטע וואַרט ביז זי ענדיקט זיך איידער איר לאָדט אַרויף אַ נײַער טעקע.",
  errorDriveNotConnected: "קיין פֿאַרבינדונג צו Google Drive איז נישט געפֿונען געוואָרן. ביטע פֿאַרבינדט זיך פֿון נײַעם.",
  errorDrivePermissionsInsufficient: "Google Drive רשויות פֿעלן. ביטע אָפּזאָגט זיך און פֿאַרבינדט זיך פֿון נײַעם כּדי צו באַשטעטיקן צוטריט צום דרײַוו.",
  errorDriveAccessFailed: "טעות בײַם צוטריט צו Google Drive. ביטע פּרוּווט ווידער שפּעטער.",
  errorDriveUnavailable: "מ׳קען נישט צוגיין צו Google Drive. ביטע פֿאַרבינדט זיך פֿון נײַעם.",
  errorDriveStorageFull: "דײַן Google Drive איז פֿול, און מ׳קען נישט אָפּהיטן דעם טראַנסקריפּט. ביטע מאַכט פּלאַץ און פּרוּווט ווידער.",
  errorMediaLost: "די טעקע איז פֿאַרלוירן געגאַנגען איידער זי איז געקומען צו דער ריי. ביטע שיקט זי ווידער.",
  errorLanguageRequiresPrivateKey: "די שפּראַך איז בלויז פֿאַראַן מיט אַ פּריוואַטן RunPod שליסל.",
  errorEndpointCheckFailed: "טעות בײַם קאָנטראָלירן Endpoint: {details}",
  errorEndpointCreated: "אַ נײַער Endpoint איז געשאַפֿן געוואָרן פֿאַר אייער שליסל. ביטע וואַרט 3 מינוט איידער איר לאָדט אַרויף טעקעס.",
  errorEndpointUpdated: "אייער Endpoint איז דערהײַנטיקט געוואָרן. ביטע וואַרט 3 מינוט איידער איר לאָדט אַרויף טעקעס.",
  errorMissingSaveAudio: "פֿעלנדיק save_audio פּאַראַמעטער",
  errorMissingLanguage: "פֿעלנדיק שפּראַך",
  errorUnsupportedLanguage: "ניט־געשטיצטע שפּראַך",
  errorMissingRunpodToken: "פֿעלנדיק RunPod טאָקען",
  errorNotAuthenticated: "נישט אױטענטיפֿיצירט מיט Google Drive",
  errorUserEmailNotFound: "באַניצער־אימעיל נישט געפֿונען",
  errorTocLoadFailed: "דורכגעפֿאַלן צו לאָדן TOC",
  errorResultsNotFound: "רעזולטאַטן־טעקע נישט געפֿונען",
  errorResultsDownloadFailed: "דורכגעפֿאַלן צו אַראָפּלאָדן רעזולטאַטן",
  errorAudioNotFound: "אַודיאָ־טעקע נישט געפֿונען",
  errorAudioDownloadFailed: "דורכגעפֿאַלן צו אַראָפּלאָדן אַודיאָ",
  errorMissingResultsId: "פֿעלנדיק results_id",
  errorMissingNewFilename: "פֿעלנדיק results_id אָדער new_filename",
  errorFilenameEmpty: "טעקע־נאָמען קען נישט זײַן ליידיק",
  errorFileNotInToc: "טעקע נישט געפֿונען אין TOC",
  errorTocUpdateFailed: "דורכגעפֿאַלן צו דערהײַנטיקן TOC",
  errorInternalServer: "אינערלעכער סערווער־טעות",
  errorBalanceFetchFailed: "דורכגעפֿאַלן צו ברענגען באַלאַנס",
  errorRunpodKeyVerifyFailed: "מיר האָבן נישט געקענט באַשטעטיקן דעם RunPod קלעף. ביטע קאָנטראָלירט דעם קלעף און פּרוּווט ווידער.",
  errorRunpodKeySaveFailed: "מיר האָבן נישט געקענט אויפֿהיטן דעם RunPod קלעף אין אײַער Google Drive. ביטע פּרוּווט ווידער.",
  errorRunpodKeyRemoveFailed: "מיר האָבן נישט געקענט אַראָפּנעמען דעם RunPod קלעף. ביטע פּרוּווט ווידער.",
  errorInvalidJson: "אומגילטיק JSON בלאָק",
  errorMissingFileSize: "פֿעלנדיק file_size",
  errorInvalidFileSize: "אומגילטיק file_size",
  tabStats: "סטאַטיסטיק",
  statsForNerds: "סטאַטיסטיק פֿאַר נערדס",
  transcriptionStatistics: "טראַנסקריפּציע־סטאַטיסטיק",
  totalTime: "געזאַמטע צײַט",
  totalWords: "געזאַמטע ווערטער",
  totalLetters: "געזאַמטע אותיות",
  wordsPerMinute: "ווערטער פּער מינוט",
  lettersPerMinute: "אותיות פּער מינוט",
  avgTimeBetweenSpeakers: "דורכשניטלעכע צײַט צווישן רעדנדיקע (סעקונדן)",
  medianTimeBetweenSpeakers: "מעדיאַנע צײַט צווישן רעדנדיקע (סעקונדן)",
  speakerTimeDistribution: "צײַט־פֿאַרטיילונג פֿאַר רעדנדיקע",
  unknownSpeaker: "ניט באַוואוסט",
  donateData: "שענקען דאַטן",
  donateDataTitle: "אַ דאַנק פֿאַר דער נדבה!",
  donateDataMessage: "מיט דער נדבה פֿון די דאַטן, באַשטעטיקט איר אַז איר האָט רשות צו באַפֿרײַען סײַ דעם קול און סײַ דעם טעקסט אונטערן ivrit.ai v2 ליצענץ.",
  donateDataCheckbox: "איך האָב געלייענט און איך בין מסכים",
  donateDataLicenseLink: "ivrit.ai v2 ליצענץ",
  donateDataSubmit: "אַרײַנגעבן",
  donateDataSuccess: "אַ דאַנק! די דאַטן זענען געשענקט געוואָרן.",
  donateDataError: "טעות בײַם שענקען דאַטן. ביטע פּרוּווט ווידער.",
  donateDataAlreadyDonated: "די דאַטן זענען שוין געשענקט געוואָרן.",
  errorMissingResultsId: "פֿעלנדיק results_id",
  errorDonateNoAudio: "אַודיאָ־טעקע נישט געפֿונען פֿאַר נדבה",
  errorDonateNoTranscript: "טראַנסקריפּציע נישט געפֿונען פֿאַר נדבה",
  errorDonateCheckboxRequired: "מען דאַרף באַשטעטיקן דעם טשעקבאָקס",
  errorAlreadyDonated: "די דאַטן זענען שוין געשענקט געוואָרן",
  // Input method labels
  inputUploadFile: "אַרויפֿלאָדן טעקע",
  inputYoutube: "YouTube",
  inputRecord: "רעקאָרד",
  // YouTube
  orSeparator: "אָדער",
  youtubeUrlPlaceholder: "קלעפּט אַ YouTube לינק דאָ",
  youtubeUrlPaste: "אַרײַנקלעפּן",
  youtubeRightsTitle: "באַשטעטיקונג פֿון רעכט",
  youtubeRightsMessage: "אַראָפּלאָדן אינהאַלט פֿון YouTube קען פֿאַרלעצן זכות היוצרים און YouTube'ס תנאי־ניצול. ביטע פֿאַרזיכערט אַז איר האָט די נויטיקע רעכט צו אַראָפּלאָדן און טראַנסקריבירן דעם אינהאַלט.",
  youtubeRightsCheckbox: "איך באַשטעטיק אַז איך האָב די רעכט צו אַראָפּלאָדן און טראַנסקריבירן דעם אינהאַלט",
  youtubeRightsSubmit: "פֿאָרזעצן",
  youtubeDownloading: "אַראָפּלאָדט אַודיאָ פֿון YouTube...",
  youtubeDownloadingProgress: "אַראָפּלאָדט... {progress}%",
  youtubeDownloadComplete: "אַראָפּלאָדן פֿאַרענדיקט. קאָנווערטירט אַודיאָ...",
  errorInvalidYoutubeUrl: "אומגילטיק YouTube לינק",
  errorYoutubeDownloadFailed: "אַראָפּלאָדן פֿון YouTube האָט דורכגעפֿאַלן. דער ווידעא איז אפֿשר נישט פֿאַראַן אָדער עס איז אַ פֿאַרבינדונגס־פּראָבלעם.",
  errorYoutubeRightsNotConfirmed: "מען דאַרף באַשטעטיקן די רעכט פֿאַרן אַראָפּלאָדן",
}

const en = {
  title: "Transcription by ivrit.ai",
  themeToggle: "Toggle light/dark mode",
  settings: "Settings",
  language: "Language",
  languageHebrew: "Hebrew",
  languageYiddish: "Yiddish",
  languageEnglish: "English",
  dropPrompt: "Drag a file here or click to choose",
  transcribe: "Transcribe",
  copyText: "Copy text",
  downloads: "Downloads",
  downloadAs: "Download as...",
  wordDocx: "Word DOCX",
  contactUs: "Want to contact us? We're here",
  donateAsk: "Want to support us?",
  privacyTos: "Privacy Policy and Terms of Use",
  settingsHeader: "Settings",
  settingsRunpod: "RunPod Settings",
  runpodKeyLabel: "RunPod API Key:",
  runpodKeyPlaceholder: "Enter your API Key",
  runpodHelpWatch: "Watch tutorial video",
  runpodHelpText: "Using a private key lets you use your private resources for faster processing.",
  settingsWithRunpodSaved: "Settings (RunPod settings saved)",
  balanceLabel: "Balance",
  remainingQuotaLabel: "Remaining quota",
  quotaLoadingError: "Error loading quota",
  howToGetMoreQuota: "Quota increase",
  hours: "hours",
  minutes: "minutes",
  loading: "Loading...",
  displaySettings: "Display settings",
  timestampsLabel: "Timestamps:",
  timestampsNone: "No timestamps",
  timestampsNoneHelp: "Only text without times",
  timestampsSegments: "Include timestamps",
  timestampsSegmentsHelp: "Start and end times, per text format",
  diarizationLabel: "Speaker separation:",
  diarizationEnabled: "Show speakers",
  diarizationEnabledHelp: "Show speaker labels and break lines on change",
  diarizationDisabled: "Hide speakers",
  diarizationDisabledHelp: "Show only text without speaker labels",
  save: "Save",
  cancel: "Cancel",
  clear: "Clear settings",
  signOut: "Sign out",
  signOutError: "We couldn't sign you out. Please check your connection and try again.",
  fileSize: "File size",
  removeFile: "Remove file",
  saveAudioInDrive: "Save audio to Google Drive",
  saveAudio: "Save audio",
  whatDoesThisMean: "What does this mean?",
  saveAudioInfoText: "Saving the audio file will soon enable synchronized reading of the transcription along with the audio.\n\nThe audio file is saved only on your Google Drive, not on our servers.",
  fileRemovedSuccess: "File removed successfully",
  fileSelectedSuccess: "File selected successfully",
  fileTooLarge: "File too large. Maximum allowed is {size}",
  usingRunpod: "Using custom RunPod settings...",
  uploading: "Uploading file...",
  uploadingProgress: "Uploading file... {progress}%",
  uploadedStarting: "File uploaded. Starting transcription...",
  uploadTranscodingPending: "Preparing audio conversion...",
  uploadTranscodingStarted: "Converting audio...",
  uploadTranscodingProgress: "Converting audio... {progress}%",
  uploadQueuePositionDetail: "Job queued at position {position} ({jobType}).",
  uploadQueueEtaDetail: "Estimated transcription start: {eta}",
  uploadTranscodingComplete: "Conversion complete. Job submitted for transcription.",
  uploadError: "Upload error. Please try again.",
  queuePosition: "In queue position {position}. Estimated start: {eta}",
  jobTypePrefix: "Job type: {jobType}",
  jobTypeShort: "short",
  jobTypeLong: "long",
  jobTypePrivate: "private",
  waitingMsg: "While you wait, note ivrit.ai is a non-profit. All our services, including this transcription service, are free.\n\nPlease consider supporting us so we can make this service available to more users.\n\nYou can support via the Patreon link at the bottom of the page.\n\nThank you!",
  transcribing: "Transcribing... {progress}%",
  statusError: "An error occurred while checking job status",
  verifyChecking: "Checking...",
  runpodSettingsSaved: "RunPod settings saved",
  runpodEndpointWait: "A new/updated endpoint is being prepared. Please wait 3 minutes before uploading.",
  settingsSaved: "Settings saved",
  settingsCleared: "All settings were cleared",
  balanceLoadingError: "Loading error",
  runpodServerConnError: "Error: cannot connect to RunPod server. Please check your connection and try again.",
  runpodVerifyError: "Error verifying RunPod settings.",
  endpointCheckError: "Error checking endpoint:",
  runpodTokenUnsavedWarning: 'RunPod token not saved. Click "Save" to apply.',
  runpodKeySavedHint: "Saved key ending in …{hint}",
  removeRunpodKey: "Remove RunPod key",
  runpodKeyRemoved: "RunPod key removed",
  runpodKeyLoadFailed: "We couldn't load your saved RunPod key. Please enter it again in settings.",
  runpodKeyMigrationFailed: "We couldn't verify your saved RunPod key. Please enter it again in settings.",
  errorReportTemplate: "If the error persists, please email info@ivrit.ai with:\n- Your email address\n- Error time: {time}\n- Error details: {details}",
  transcriptFooter: "Transcribed using ivrit.ai's transcription service",
  copySuccess: "Text copied to clipboard",
  docxLibMissing: "Document library not loaded. Check connection and try again.",
  docxCreateError: "Error creating Word file. Please try again.",
  exportError: "Error exporting transcription data",
  exitWarning: "Transcription is still running. Leaving will stop it. Are you sure you want to leave?",
  transcriptHeaderDocx: "Transcription",
  speaker: "Speaker {num}",
  speakerUnknown: "Unknown speaker",
  errorPrefix: "Error",
  unitBytes: "Bytes",
  unitKB: "KB",
  unitMB: "MB",
  unitGB: "GB",
  textFormatSegmentsTitle: "Text format: separate paragraphs",
  textFormatContinuousTitle: "Text format: continuous text",
  filesSelectedCount: "{count} files selected",
  filesSelectedSuccess: "{count} files selected successfully",
  batchStarting: "Starting batch of {count} files...",
  batchUploading: "Uploading {index}/{total}: {filename}",
  batchQueued: "{count} files submitted for transcription. Results will appear in \"My Files\".",
  batchTranscribing: "Transcribing ({index}/{total}) {filename} · {progress}%",
  batchDone: "Batch complete",
  docxDownloaded: "DOCX downloaded: {filename}",
  tabTranscribe: "New Transcription",
  tabMyFiles: "My Files",
  viewTitle: "Transcribe",
  tabViewer: "Viewer",
  openDataDir: "Copy Folder Path",
  dataDirCopied: "Path copied to clipboard",
  dataDirWarning: "Modifying, deleting, or renaming files in this directory can irreversibly damage your stored data.\n\nProceed with extreme caution.\n\nContinue?",
  filesLoading: "Loading files...",
  filesEmpty: "You haven't saved any transcriptions yet",
  filesLoadError: "Error loading files",
  loadingFile: "Loading file...",
  filesDownloading: "Downloading file...",
  filesDownloadSuccess: "File downloaded successfully",
  filesDownloadError: "Error downloading file",
  backToFiles: "Back to list",
  renameFile: "Rename",
  fileRenamedSuccess: "File renamed successfully",
  renameError: "Error renaming file",
  saving: "Saving...",
  discardEditsConfirm: "Discard your unsaved changes to this transcript?",
  editsLoadError: "We couldn't load your saved edits for this transcript. Please reload the page and try again.",
  editorLoadError: "The editor couldn't be loaded. Please check your connection and reload the page.",
  restoreEditDraftConfirm: "You have unsaved changes to this transcript from a previous session. Restore them? (Cancel discards them.)",
  transcriptionQueued: "File sent for transcription successfully.",
  transcriptionInProgress: "Transcription in progress",
  batchFailed: "All files failed",
  deleteFile: "Delete file",
  quotaRefunded: "Minutes returned to your quota",
  deleteConfirm: 'Are you sure you want to delete "{filename}"?\n\nThis action cannot be undone.',
  fileDeletedSuccess: "File deleted successfully",
  deleteError: "Error deleting file",
  deleting: "Deleting...",
  recordAudio: "Record audio",
  recordMicOnly: "Record microphone only",
  recordMicAndScreen: "Record microphone + screen",
  recordScreenOnly: "Record screen only",
  stopRecording: "Stop recording",
  downloadRecording: "Download recording",
  transcribeRecording: "Transcribe recording",
  discardRecording: "Discard recording",
  recordingDownloaded: "Recording downloaded successfully",
  recordingDiscarded: "Recording discarded",
  recordingNotBackedUp: "This recording can't be backed up in your browser, so it is kept in memory only. Download it when you finish recording.",
  recoveredRecordingFound: "You have a recording that was never sent for transcription",
  recoveredRecordingInterrupted: "You have a recording that was interrupted before it finished",
  recoveredRecordingHint: "It is saved in your browser. You can transcribe it now, download it to your computer, or discard it.",
  recordingReadyToTranscribe: "Recording is ready for transcription. Click \"Transcribe\" to continue.",
  recordingReadFailed: "The recording could not be loaded right now, but it is saved in your browser. Reload the page to recover it.",
  pushPromptTitle: "Get a notification when your transcription is ready?",
  pushPromptBody: "Transcription continues even if you close your browser. We can notify you the moment it is ready.",
  pushPromptYes: "Yes, notify me",
  pushPromptNo: "Not now",
  pushPromptDontAsk: "Don't ask me again",
  pushEnabled: "We'll notify you when your transcription is ready.",
  pushDenied: "We couldn't turn on notifications. You can allow them in your browser settings.",
  installApp: "Install",
  installTitle: "Install the app",
  installWhy: "The app opens from your home screen like any other app.",
  installWhyNotifications: "On iPhone, installing it is also the only way to get a notification when your transcription is ready.",
  installStepsIos: "Open the Share menu in Safari's toolbar and choose \"Add to Home Screen\".",
  installDone: "Got it",
  installed: "The app has been installed.",
  micPermissionDenied: "Microphone or system audio access was denied. Please allow access in your browser settings.",
  micError: "Error accessing audio. Please ensure your devices are connected and enabled.",
  recordingMicOnlyWarning: "Recording microphone only (system audio not selected)",
  screenAudioNotSelected: "System audio not selected. Please check \"Share audio\" in the dialog.",
  screenAudioError: "Error accessing system audio. Please try again.",
  // Server error messages
  errorJobAlreadyActive: "You already have a job queued or in progress. Please wait for it to complete before uploading a new file.",
  errorRateLimitExceeded: "You have exceeded the free usage limit. Please wait {minutes} minutes before uploading a new file, or use a private key following the instructions in this video: https://youtu.be/xr8RQRFERLs",
  errorFileTooLargeForFreeService: "The requested file is too large and exceeds the total free usage limit. Please use a private key following the instructions in this video: https://youtu.be/xr8RQRFERLs",
  errorServerBusy: "The server is currently busy. Please try again later.",
  errorDrivePermissionsRequired: "The service requires Google Drive permissions to save your transcriptions. Please approve all requested permissions to continue.",
  errorServiceUnavailable: "The service is currently unavailable. Please try again later.",
  errorNoFileSelected: "No file selected. Please choose a file to upload.",
  errorEmptyFilename: "The filename is empty. Please choose a valid file.",
  errorFileTooLarge: "File too large. The maximum allowed size is {size}.",
  errorUploadFailed: "File upload failed: {details}",
  errorUnsupportedFileType: "File type {type} is not supported. Please upload a valid audio or video file.",
  errorTranscodingFailed: "File conversion failed. The file type may not be supported or the file may be corrupted. Please try with a different file.",
  errorCannotReadDuration: "Cannot read file duration. Please ensure the file is valid and try again.",
  errorFileTooLong: "File is too long. The maximum allowed duration is {maxHours} hours ({maxSeconds} hours), but your file is {fileHours} hours.",
  errorBatchLimitReached: "You have reached the parallel job limit. Please wait for some jobs to finish before uploading more files.",
  batchLimitExceeded: "Too many files selected. Only the first {limit} files will be processed.",
  errorTranscodingJobActive: "You already have a file being converted. Please wait for it to complete before uploading a new file.",
  errorDriveNotConnected: "No connection to Google Drive detected. Please reconnect.",
  errorDrivePermissionsInsufficient: "Google Drive permissions are insufficient. Please disconnect and reconnect to authorize Drive access.",
  errorDriveAccessFailed: "Error accessing Google Drive. Please try again later.",
  errorDriveUnavailable: "Cannot access Google Drive. Please reconnect.",
  errorDriveStorageFull: "Your Google Drive is full, so the transcript cannot be saved. Please free up space and try again.",
  errorMediaLost: "The file was lost before its turn came. Please send it again.",
  errorLanguageRequiresPrivateKey: "This language is only available for use with a private RunPod key.",
  errorEndpointCheckFailed: "Error checking endpoint: {details}",
  errorEndpointCreated: "A new endpoint was created for your key. Please wait 3 minutes before uploading files.",
  errorEndpointUpdated: "Your endpoint has been updated. Please wait 3 minutes before uploading files.",
  errorMissingSaveAudio: "Missing save_audio parameter",
  errorMissingLanguage: "Missing language",
  errorUnsupportedLanguage: "Unsupported language",
  errorMissingRunpodToken: "Missing RunPod token",
  errorNotAuthenticated: "Not authenticated with Google Drive",
  errorUserEmailNotFound: "User email not found",
  errorTocLoadFailed: "Failed to load TOC",
  errorResultsNotFound: "Results file not found",
  errorResultsDownloadFailed: "Failed to download results",
  errorAudioNotFound: "Audio file not found",
  errorAudioDownloadFailed: "Failed to download audio",
  errorMissingResultsId: "Missing results_id",
  errorMissingNewFilename: "Missing results_id or new_filename",
  errorFilenameEmpty: "Filename cannot be empty",
  errorFileNotInToc: "File not found in TOC",
  errorTocUpdateFailed: "Failed to update TOC",
  errorInternalServer: "Internal server error",
  errorBalanceFetchFailed: "Failed to fetch balance",
  errorRunpodKeyVerifyFailed: "We couldn't verify this RunPod key. Please check the key and try again.",
  errorRunpodKeySaveFailed: "We couldn't save your RunPod key to your Google Drive. Please try again.",
  errorRunpodKeyRemoveFailed: "We couldn't remove your RunPod key. Please try again.",
  errorInvalidJson: "Invalid JSON body",
  errorMissingFileSize: "Missing file_size",
  errorInvalidFileSize: "Invalid file_size",
  tabStats: "Statistics",
  statsForNerds: "Stats for Nerds",
  transcriptionStatistics: "Transcription Statistics",
  totalTime: "Total Time",
  totalWords: "Total Words",
  totalLetters: "Total Letters",
  wordsPerMinute: "Words Per Minute",
  lettersPerMinute: "Letters Per Minute",
  avgTimeBetweenSpeakers: "Average Time Between Speakers (seconds)",
  medianTimeBetweenSpeakers: "Median Time Between Speakers (seconds)",
  speakerTimeDistribution: "Speaker Time Distribution",
  unknownSpeaker: "Unknown",
  donateData: "Donate data",
  donateDataTitle: "Thank you for contributing!",
  donateDataMessage: "By contributing this data, you confirm that you have permissions to release both its voice and text under the ivrit.ai v2 license.",
  donateDataCheckbox: "I have read and agree",
  donateDataLicenseLink: "ivrit.ai v2 license",
  donateDataSubmit: "Submit",
  donateDataSuccess: "Thank you! The data was donated successfully.",
  donateDataError: "Error donating data. Please try again.",
  donateDataAlreadyDonated: "This data has already been donated.",
  errorMissingResultsId: "Missing results_id",
  errorDonateNoAudio: "Audio file not found for donation",
  errorDonateNoTranscript: "Transcription not found for donation",
  errorDonateCheckboxRequired: "Checkbox must be checked",
  errorAlreadyDonated: "This data has already been donated",
  // Input method labels
  inputUploadFile: "Upload File",
  inputYoutube: "YouTube",
  inputRecord: "Record",
  // YouTube
  orSeparator: "or",
  youtubeUrlPlaceholder: "Paste a YouTube link here",
  youtubeUrlPaste: "Paste",
  youtubeRightsTitle: "Rights Confirmation",
  youtubeRightsMessage: "Downloading content from YouTube may violate copyright and YouTube's Terms of Service. Please ensure you have the necessary rights to download and transcribe this content.",
  youtubeRightsCheckbox: "I confirm I have the rights to download and transcribe this content",
  youtubeRightsSubmit: "Continue",
  youtubeDownloading: "Downloading audio from YouTube...",
  youtubeDownloadingProgress: "Downloading... {progress}%",
  youtubeDownloadComplete: "Download complete. Converting audio...",
  errorInvalidYoutubeUrl: "Invalid YouTube URL",
  errorYoutubeDownloadFailed: "Failed to download from YouTube. The video may be unavailable or there may be a connection issue.",
  errorYoutubeRightsNotConfirmed: "You must confirm rights before downloading",
}

const RESOURCES = { he, yi, en };
let current = "he";

export function setLanguage(lang) {
  current = RESOURCES[lang] ? lang : "he";
}

export function language() {
  return current;
}

export function tr(key, vars) {
  const value = RESOURCES[current]?.[key] ?? RESOURCES.he[key] ?? key;
  return String(value).replace(/\{(.*?)\}/g, (_, name) => (vars && name in vars ? vars[name] : `{${name}}`));
}

// The words for a server's refusal ({error, i18n_key, i18n_vars, details}).
export function serverError(data, fallback = "errorInternalServer") {
  if (!data) return tr(fallback);
  const key = data.i18n_key || (typeof data.error === "string" && data.error.startsWith("error") ? data.error : null);
  if (!key) return typeof data.error === "string" ? data.error : tr(fallback);
  return tr(key, { ...(data.i18n_vars || {}), details: data.details ?? "" });
}

// Words the app's own screens for transcribing add (web/transcription/view.js).
const NATIVE = {
  he: {
    uploadFile: "העלאת קובץ", record: "הקלטה", newTitle: "תמלול חדש", filesWord: "קבצים",
    statusQueuedAt: "בתור · מקום {position}", statusQueued: "בתור", statusTranscribing: "מתמלל", statusTranscribingAt: "מתמלל · {progress}%",
    statusUploading: "מעלה · {progress}%", statusPreparing: "מכין · {progress}%", statusPreparingStart: "מכין", statusFailed: "נכשל",
    etaIn: "בעוד כ־{eta}", transcribeLanguage: "שפת התמלול", chooseFiles: "בחירת קבצים", addFiles: "הוספת קבצים",
    open: "פתיחה", back: "הקבצים שלי", display: "תצוגה", export: "ייצוא", edit: "עריכה", copy: "העתקה", statistics: "סטטיסטיקות",
    delete: "מחיקה", donate: "תרומה למאגר", showSpeakers: "דוברים", showTimestamps: "קודי זמן", layoutWords: "פריסה",
    layoutContinuous: "רציף", layoutSegments: "פסקאות", viewEdited: "ערוך", viewOriginal: "מקור", viewCompared: "השוואה",
    editing: "עריכת התמלול", editHint: "מקישים על משפט כדי לתקן אותו, ועל שם דובר כדי לשנות אותו.",
    renameSpeaker: "שינוי שם הדובר", assignSpeaker: "שיוך לדובר", assignBlock: "כל הקטע הזה לדובר", speakerName: "שם",
    nameTaken: "השם הזה כבר שייך לדובר אחר", reset: "חזרה לשם המקורי", edited: "נערך", wordsCount: "{count} מילים",
    emptyTitle: "עוד אין כאן תמלולים", emptyBody: "מעלים קובץ שמע או וידאו, או מקליטים, ומקבלים תמלול עם דוברים, שנשמר ב-Google Drive שלכם.",
    dropHere: "שחררו כאן כדי לתמלל", gone: "התמלול הזה לא נמצא", quotaLine: "נותרו {amount} השבוע", balanceLine: "יתרה ב-RunPod: {amount}",
    speakerTime: "זמן דיבור", avgGap: "הפסקה ממוצעת בין דוברים", seconds: "{value} שניות", recordingTime: "מקליטים",
    stop: "עצירה", recorded: "הקלטה מ־{time}", unsavedLeave: "השינויים בתמלול לא נשמרו. לצאת בלי לשמור?",
    untitled: "ללא שם",
    fileLoadError: "לא הצלחנו לפתוח את התמלול", discardEdits: "ביטול השינויים", copyError: "ההעתקה לא הצליחה", subtitles: "כתוביות", jsonWithTimes: "המשפטים עם הזמנים", editsSaved: "השינויים נשמרו", editsSaveError: "לא הצלחנו לשמור את השינויים", textFile: "טקסט", fileQueued: "הקובץ נשלח לתמלול. הוא יופיע כאן כשיהיה מוכן.",
  },
  yi: {
    uploadFile: "אַרויפֿלאָדן אַ טעקע", record: "רעקאָרדירן", newTitle: "נײַע טראַנסקריפּציע", filesWord: "טעקעס",
    statusQueuedAt: "אין דער ריי · אָרט {position}", statusQueued: "אין דער ריי", statusTranscribing: "טראַנסקריבירט", statusTranscribingAt: "טראַנסקריבירט · {progress}%",
    statusUploading: "לאָדט אַרויף · {progress}%", statusPreparing: "גרייט צו · {progress}%", statusPreparingStart: "גרייט צו", statusFailed: "דורכגעפֿאַלן",
    etaIn: "אין בערך {eta}", transcribeLanguage: "שפּראַך פֿון דער טראַנסקריפּציע", chooseFiles: "אויסקלײַבן טעקעס", addFiles: "צוגעבן טעקעס",
    open: "עפֿענען", back: "מײַנע טעקעס", display: "אויסזען", export: "עקספּאָרטירן", edit: "רעדאַגירן", copy: "קאָפּירן", statistics: "סטאַטיסטיק",
    delete: "אויסמעקן", donate: "בײַשטײַערן", showSpeakers: "רעדנדיקע", showTimestamps: "צײַט־קאָדן", layoutWords: "אויסשטעל",
    layoutContinuous: "אין איינעם", layoutSegments: "פּאַראַגראַפֿן", viewEdited: "רעדאַגירט", viewOriginal: "אָריגינעל", viewCompared: "פֿאַרגלײַכן",
    editing: "רעדאַגירן די טראַנסקריפּציע", editHint: "טוט אַ טאַפּ אויף אַ זאַץ כּדי צו פֿאַרריכטן, און אויף אַ נאָמען כּדי צו בײַטן.",
    renameSpeaker: "בײַטן דעם נאָמען", assignSpeaker: "צושרײַבן צו", assignBlock: "דער גאַנצער אָפּשניט צו", speakerName: "נאָמען",
    nameTaken: "דער נאָמען געהערט שוין צו אַן אַנדער רעדנדיקן", reset: "צוריק צום אָריגינעלן נאָמען", edited: "רעדאַגירט", wordsCount: "{count} ווערטער",
    emptyTitle: "נאָך קיין טראַנסקריפּציעס", emptyBody: "לאָדט אַרויף אַ טעקע אָדער רעקאָרדירט, און באַקומט אַ טראַנסקריפּציע מיט רעדנדיקע, אין אײַער Google Drive.",
    dropHere: "לאָזט אַראָפּ דאָ צו טראַנסקריבירן", gone: "די טראַנסקריפּציע איז ניט געפֿונען", quotaLine: "{amount} געבליבן די וואָך", balanceLine: "RunPod באַלאַנס: {amount}",
    speakerTime: "רעד־צײַט", avgGap: "דורכשניטלעכע הפֿסקה צווישן רעדנדיקע", seconds: "{value} סעקונדעס", recordingTime: "רעקאָרדירט",
    stop: "אָפּשטעלן", recorded: "רעקאָרדירונג פֿון {time}", unsavedLeave: "די ענדערונגען זענען ניט אויפֿגעהיט. אַרויסגיין אָן אויפֿהיטן?",
    untitled: "אָן נאָמען",
    fileLoadError: "מיר האָבן ניט געקענט עפֿענען די טראַנסקריפּציע", discardEdits: "אַוועקוואַרפֿן די ענדערונגען", copyError: "קאָפּירן איז ניט געלונגען", subtitles: "סובטיטלען", jsonWithTimes: "די זאַצן מיט די צײַטן", editsSaved: "די ענדערונגען זענען אויפֿגעהיט", editsSaveError: "מיר האָבן ניט געקענט אויפֿהיטן די ענדערונגען", textFile: "טעקסט", fileQueued: "די טעקע איז געשיקט געוואָרן צום טראַנסקריבירן. זי וועט זיך באַווײַזן דאָ.",
  },
  en: {
    uploadFile: "Upload a file", record: "Record", newTitle: "New transcription", filesWord: "files",
    statusQueuedAt: "Queued · #{position}", statusQueued: "Queued", statusTranscribing: "Transcribing", statusTranscribingAt: "Transcribing · {progress}%",
    statusUploading: "Uploading · {progress}%", statusPreparing: "Preparing · {progress}%", statusPreparingStart: "Preparing", statusFailed: "Failed",
    etaIn: "in about {eta}", transcribeLanguage: "Language spoken", chooseFiles: "Choose files", addFiles: "Add files",
    open: "Open", back: "My files", display: "Display", export: "Export", edit: "Edit", copy: "Copy", statistics: "Statistics",
    delete: "Delete", donate: "Donate", showSpeakers: "Speakers", showTimestamps: "Timestamps", layoutWords: "Layout",
    layoutContinuous: "Continuous", layoutSegments: "Paragraphs", viewEdited: "Edited", viewOriginal: "Original", viewCompared: "Compare",
    editing: "Editing the transcript", editHint: "Tap a sentence to correct it, and a speaker's name to change it.",
    renameSpeaker: "Rename speaker", assignSpeaker: "Assign to", assignBlock: "This whole passage to", speakerName: "Name",
    nameTaken: "Another speaker already has that name", reset: "Back to the original name", edited: "Edited", wordsCount: "{count} words",
    emptyTitle: "No transcripts yet", emptyBody: "Upload an audio or video file, or record, and get a transcript with speakers, kept in your Google Drive.",
    dropHere: "Drop here to transcribe", gone: "This transcript was not found", quotaLine: "{amount} left this week", balanceLine: "RunPod balance: {amount}",
    speakerTime: "Speaking time", avgGap: "Average pause between speakers", seconds: "{value} seconds", recordingTime: "Recording",
    stop: "Stop", recorded: "Recording from {time}", unsavedLeave: "The transcript has unsaved changes. Leave without saving?",
    untitled: "Untitled",
    fileLoadError: "Could not open the transcript", discardEdits: "Discard changes", copyError: "Could not copy", subtitles: "Subtitles", jsonWithTimes: "The sentences with their times", editsSaved: "Changes saved", editsSaveError: "Could not save the changes", textFile: "Text", fileQueued: "Sent for transcription. It will appear here when ready.",
  },
};
Object.assign(he, NATIVE.he);
Object.assign(yi, NATIVE.yi);
Object.assign(en, NATIVE.en);
